### Localhost: Get all contacts
GET http://localhost:8080/contacts

### Localhost: Get single contact by ID (replace with a real _id from your MongoDB)
GET http://localhost:8080/contacts/6ab7d9f33faf00b30c49c32d


### =========================================================
### Production (Render): https://cse-341-web-services-clqy.onrender.com/
### =========================================================

### Render: Get all contacts
GET https://cse-341-web-services-clqy.onrender.com/contacts

### Render: Get single contact by ID
GET https://cse-341-web-services-clqy.onrender.com/contacts/6ab7d9f33faf00b30c49c32d 
